import { useRef, useState, useEffect } from "react";
import { motion } from "framer-motion";
import { ArrowRight, Upload, Wand2, X } from "lucide-react";
import { useNavigate } from "@tanstack/react-router";
import { GenerateModal } from "./GenerateModal";
import { templates } from "./Templates";
import { getAuthToken } from "@/lib/auth";import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";

export function Hero() {
  const fileInputRef = useRef(null);
  const errorTimeoutRef = useRef(null);
  const [file, setFile] = useState(null);
  const [showError, setShowError] = useState(false);
  const [randomTemplate, setRandomTemplate] = useState(templates[0]);
  const navigate = useNavigate();

  useEffect(() => {
    // Pick a new random template whenever the modal might be closed or on initial load
    setRandomTemplate(templates[Math.floor(Math.random() * templates.length)]);
  }, [file]);

  const handleUploadClick = () => {
    fileInputRef.current?.click();
  };

  const handleGenerateClick = (e) => {
    const isLoggedIn = !!getAuthToken();

    if (!isLoggedIn) {
      e.preventDefault();
      e.stopPropagation();
      navigate({ to: "/signin" });
      return;
    }

    if (!file) {
      e.preventDefault();
      e.stopPropagation();
      setShowError(true);
      if (errorTimeoutRef.current) {
        clearTimeout(errorTimeoutRef.current);
      }
      errorTimeoutRef.current = setTimeout(() => {
        setShowError(false);
      }, 5000);
    } else {
      setShowError(false);
      // Pick a new random template on every click to ensure variety
      setRandomTemplate(templates[Math.floor(Math.random() * templates.length)]);
    }
  };

  return (/*#__PURE__*/
    _jsxs("section", { id: "hero", className: "relative pt-24 pb-32 overflow-hidden", children: [/*#__PURE__*/

      _jsx("div", { "aria-hidden": true, className: "absolute inset-0 bg-hero pointer-events-none" }), /*#__PURE__*/
      _jsx("div", { "aria-hidden": true, className: "absolute inset-0 grid-pattern opacity-40 [mask-image:radial-gradient(ellipse_at_center,black,transparent_70%)]" }), /*#__PURE__*/
      _jsx("div", { "aria-hidden": true, className: "absolute -top-40 -left-20 w-[500px] h-[500px] rounded-full bg-primary/30 blur-3xl animate-aurora" }), /*#__PURE__*/
      _jsx("div", { "aria-hidden": true, className: "absolute top-20 -right-20 w-[500px] h-[500px] rounded-full bg-accent/20 blur-3xl animate-aurora", style: { animationDelay: "-6s" } }), /*#__PURE__*/

      _jsxs("div", { className: "relative mx-auto max-w-5xl px-6 text-center", children: [/*#__PURE__*/
        _jsxs(motion.div, {
          initial: { opacity: 0, y: 20 },
          animate: { opacity: 1, y: 0 },
          transition: { duration: 0.6 },
          className: "inline-flex items-center gap-2 glass rounded-full px-4 py-1.5 text-xs text-muted-foreground mb-8", children: [/*#__PURE__*/

          _jsx("span", { className: "w-1.5 h-1.5 rounded-full bg-accent animate-glow" }), "Powered by next-gen AI \xB7 Resume to portfolio in 30s"] }

        ), /*#__PURE__*/

        _jsxs(motion.h1, {
          initial: { opacity: 0, y: 30 },
          animate: { opacity: 1, y: 0 },
          transition: { duration: 0.7, delay: 0.1 },
          className: "text-5xl md:text-7xl font-bold tracking-tight leading-[1.05]", children: [
          "Your resume.", /*#__PURE__*/
          _jsx("br", {}), "A stunning portfolio.", /*#__PURE__*/
          _jsx("br", {}), /*#__PURE__*/
          _jsx("span", { className: "text-gradient", children: "Generated by AI." })] }
        ), /*#__PURE__*/

        _jsx(motion.p, {
          initial: { opacity: 0, y: 30 },
          animate: { opacity: 1, y: 0 },
          transition: { duration: 0.7, delay: 0.2 },
          className: "mt-8 text-lg md:text-xl text-muted-foreground max-w-2xl mx-auto", children:
          "Upload your resume \u2014 our AI crafts a premium, responsive portfolio site with hand-tuned content, layouts, and color in seconds. Publish, share, ship." }


        ), /*#__PURE__*/

        _jsxs("div", { className: "mt-10 flex flex-col items-center justify-center gap-5", children: [/*#__PURE__*/
          _jsxs(motion.div, {
            initial: { opacity: 0, y: 30 },
            animate: { opacity: 1, y: 0 },
            transition: { duration: 0.7, delay: 0.3 },
            className: "flex flex-col sm:flex-row items-center justify-center gap-3", children: [/*#__PURE__*/

            _jsx(GenerateModal, {
              templateId: randomTemplate.id,
              templateName: randomTemplate.name,
              initialFile: file, children: /*#__PURE__*/

              _jsxs("button", {
                onClick: handleGenerateClick,
                className: "group inline-flex items-center gap-2 bg-aurora text-background font-medium px-6 py-3.5 rounded-xl glow hover:scale-[1.02] transition-transform", children: [/*#__PURE__*/

                _jsx(Wand2, { className: "w-4 h-4" }), "Generate Portfolio with AI", /*#__PURE__*/

                _jsx(ArrowRight, { className: "w-4 h-4 group-hover:translate-x-1 transition-transform" })] }
              ) }
            ), /*#__PURE__*/
            _jsxs("div", { className: "flex items-center gap-2", children: [/*#__PURE__*/
              _jsxs("button", {
                onClick: handleUploadClick,
                className: `inline-flex items-center gap-2 font-medium px-6 py-3.5 rounded-xl transition-all cursor-pointer ${
                showError ?
                "bg-red-500/10 text-red-400 border border-red-500/50 hover:bg-red-500/20" :
                "glass text-foreground hover:bg-white/5"}`, children: [/*#__PURE__*/


                _jsx(Upload, { className: "w-4 h-4 shrink-0" }), /*#__PURE__*/
                _jsx("span", { className: "truncate max-w-[200px]", children: file ? file.name : "Upload Resume" })] }
              ),
              file && /*#__PURE__*/
              _jsx("button", {
                onClick: () => {
                  setFile(null);
                  if (fileInputRef.current) fileInputRef.current.value = "";
                },
                className: "inline-flex items-center justify-center p-3.5 glass text-muted-foreground hover:text-red-400 hover:bg-red-400/10 rounded-xl transition-all cursor-pointer",
                title: "Remove file", children: /*#__PURE__*/

                _jsx(X, { className: "w-5 h-5" }) }
              )] }

            ), /*#__PURE__*/
            _jsx("input", {
              type: "file",
              ref: fileInputRef,
              className: "hidden",
              accept: ".pdf,.doc,.docx,.ppt,.pptx,application/pdf,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/vnd.ms-powerpoint,application/vnd.openxmlformats-officedocument.presentationml.presentation",
              onChange: (e) => {
                const selectedFile = e.target.files?.[0];
                if (selectedFile) {
                  setFile(selectedFile);
                  setShowError(false);
                  console.log("File selected:", selectedFile.name);
                  // Update random template when a new file is uploaded
                  setRandomTemplate(templates[Math.floor(Math.random() * templates.length)]);
                }
              } }
            )] }
          ), /*#__PURE__*/

          _jsx(motion.a, {
            href: "#templates",
            initial: { opacity: 0, y: 30 },
            animate: { opacity: 1, y: 0 },
            transition: { duration: 0.7, delay: 0.4 },
            className: "text-sm font-medium text-muted-foreground hover:text-foreground underline decoration-muted-foreground/30 hover:decoration-foreground underline-offset-4 transition-all", children:
            "or use a prebuilt template" }

          )] }
        )] }
      )] }
    ));

}