/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PreviewTerminalRouteImport } from './routes/preview.terminal'
import { Route as PreviewNotionRouteImport } from './routes/preview.notion'
import { Route as PreviewGlassRouteImport } from './routes/preview.glass'
import { Route as PreviewFuturisticRouteImport } from './routes/preview.futuristic'
import { Route as PreviewDarkRouteImport } from './routes/preview.dark'
import { Route as PreviewBentoRouteImport } from './routes/preview.bento'

const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewTerminalRoute = PreviewTerminalRouteImport.update({
  id: '/preview/terminal',
  path: '/preview/terminal',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewNotionRoute = PreviewNotionRouteImport.update({
  id: '/preview/notion',
  path: '/preview/notion',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewGlassRoute = PreviewGlassRouteImport.update({
  id: '/preview/glass',
  path: '/preview/glass',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewFuturisticRoute = PreviewFuturisticRouteImport.update({
  id: '/preview/futuristic',
  path: '/preview/futuristic',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewDarkRoute = PreviewDarkRouteImport.update({
  id: '/preview/dark',
  path: '/preview/dark',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewBentoRoute = PreviewBentoRouteImport.update({
  id: '/preview/bento',
  path: '/preview/bento',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/templates': typeof TemplatesRoute
  '/preview/bento': typeof PreviewBentoRoute
  '/preview/dark': typeof PreviewDarkRoute
  '/preview/futuristic': typeof PreviewFuturisticRoute
  '/preview/glass': typeof PreviewGlassRoute
  '/preview/notion': typeof PreviewNotionRoute
  '/preview/terminal': typeof PreviewTerminalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/templates': typeof TemplatesRoute
  '/preview/bento': typeof PreviewBentoRoute
  '/preview/dark': typeof PreviewDarkRoute
  '/preview/futuristic': typeof PreviewFuturisticRoute
  '/preview/glass': typeof PreviewGlassRoute
  '/preview/notion': typeof PreviewNotionRoute
  '/preview/terminal': typeof PreviewTerminalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/templates': typeof TemplatesRoute
  '/preview/bento': typeof PreviewBentoRoute
  '/preview/dark': typeof PreviewDarkRoute
  '/preview/futuristic': typeof PreviewFuturisticRoute
  '/preview/glass': typeof PreviewGlassRoute
  '/preview/notion': typeof PreviewNotionRoute
  '/preview/terminal': typeof PreviewTerminalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profile'
    | '/signin'
    | '/signup'
    | '/templates'
    | '/preview/bento'
    | '/preview/dark'
    | '/preview/futuristic'
    | '/preview/glass'
    | '/preview/notion'
    | '/preview/terminal'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/profile'
    | '/signin'
    | '/signup'
    | '/templates'
    | '/preview/bento'
    | '/preview/dark'
    | '/preview/futuristic'
    | '/preview/glass'
    | '/preview/notion'
    | '/preview/terminal'
  id:
    | '__root__'
    | '/'
    | '/profile'
    | '/signin'
    | '/signup'
    | '/templates'
    | '/preview/bento'
    | '/preview/dark'
    | '/preview/futuristic'
    | '/preview/glass'
    | '/preview/notion'
    | '/preview/terminal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProfileRoute: typeof ProfileRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  TemplatesRoute: typeof TemplatesRoute
  PreviewBentoRoute: typeof PreviewBentoRoute
  PreviewDarkRoute: typeof PreviewDarkRoute
  PreviewFuturisticRoute: typeof PreviewFuturisticRoute
  PreviewGlassRoute: typeof PreviewGlassRoute
  PreviewNotionRoute: typeof PreviewNotionRoute
  PreviewTerminalRoute: typeof PreviewTerminalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/terminal': {
      id: '/preview/terminal'
      path: '/preview/terminal'
      fullPath: '/preview/terminal'
      preLoaderRoute: typeof PreviewTerminalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/notion': {
      id: '/preview/notion'
      path: '/preview/notion'
      fullPath: '/preview/notion'
      preLoaderRoute: typeof PreviewNotionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/glass': {
      id: '/preview/glass'
      path: '/preview/glass'
      fullPath: '/preview/glass'
      preLoaderRoute: typeof PreviewGlassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/futuristic': {
      id: '/preview/futuristic'
      path: '/preview/futuristic'
      fullPath: '/preview/futuristic'
      preLoaderRoute: typeof PreviewFuturisticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/dark': {
      id: '/preview/dark'
      path: '/preview/dark'
      fullPath: '/preview/dark'
      preLoaderRoute: typeof PreviewDarkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/bento': {
      id: '/preview/bento'
      path: '/preview/bento'
      fullPath: '/preview/bento'
      preLoaderRoute: typeof PreviewBentoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProfileRoute: ProfileRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  TemplatesRoute: TemplatesRoute,
  PreviewBentoRoute: PreviewBentoRoute,
  PreviewDarkRoute: PreviewDarkRoute,
  PreviewFuturisticRoute: PreviewFuturisticRoute,
  PreviewGlassRoute: PreviewGlassRoute,
  PreviewNotionRoute: PreviewNotionRoute,
  PreviewTerminalRoute: PreviewTerminalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
